--CRIAR UM BANCO DE DADOS
--O COMANDO "DROP DATABASE" DELETA UM BANCO DE DADOS
CREATE DATABASE PET;

--CRIAR TABELA 
CREATE TABLE CACHORROS (
    ID_RACA INT NOT NULL PRIMARY KEY,
    NOME_RACA VARCHAR (30) NOT NULL,
    TIPO_PELO VARCHAR (10) NOT NULL,
    PORTE VARCHAR (10) NOT NULL,
    PAIS_ORIGEM VARCHAR (10) NOT NULL,
)

CREATE TABLE GATOS (
    ID_RACA INT NOT NULL PRIMARY KEY,
    NOME_RACA VARCHAR (30) NOT NULL,
    TIPO_PELO VARCHAR (10) NOT NULL,
    PAIS_ORIGEM VARCHAR (10) NOT NULL,
)

--ALTERAR DADO DA TABELA
ALTER TABLE CACHORROS ALTER COLUMN PAIS_ORIGEM VARCHAR (30) NOT NULL;

--INSERIR INFORMAÇÕES NA TABELA "CACHORROS"
INSERT INTO CACHORROS (ID_RACA, NOME_RACA, TIPO_PELO, PORTE, PAIS_ORIGEM)
VALUES ('1', 'AKITA', 'CURTO', 'GRANDE', 'JAPÃO');

INSERT INTO CACHORROS (ID_RACA, NOME_RACA, TIPO_PELO, PORTE, PAIS_ORIGEM)
VALUES ('2', 'AMERICAN BULLY', 'CURTO', 'GRANDE', 'EUA');

INSERT INTO CACHORROS (ID_RACA, NOME_RACA, TIPO_PELO, PORTE, PAIS_ORIGEM)
VALUES ('3', 'BASSET HOUND', 'CURTO', 'MÉDIO', 'FRANÇA');

INSERT INTO CACHORROS (ID_RACA, NOME_RACA, TIPO_PELO, PORTE, PAIS_ORIGEM)
VALUES ('4', 'BEAGLE', 'CURTO', 'MÉDIO', 'INGLATERRA');

INSERT INTO CACHORROS (ID_RACA, NOME_RACA, TIPO_PELO, PORTE, PAIS_ORIGEM)
VALUES ('5', 'BORDER COLLIE', 'MÉDIO', 'GRANDE', 'INGLATERRA');

INSERT INTO CACHORROS (ID_RACA, NOME_RACA, TIPO_PELO, PORTE, PAIS_ORIGEM)
VALUES ('6', 'BOXER', 'CURTO', 'GRANDE', 'ALEMANHA');

INSERT INTO CACHORROS (ID_RACA, NOME_RACA, TIPO_PELO, PORTE, PAIS_ORIGEM)
VALUES ('7', 'BULDOG FRANCÊS', 'CURTO', 'PEQUENO', 'INGLATERRA');

INSERT INTO CACHORROS (ID_RACA, NOME_RACA, TIPO_PELO, PORTE, PAIS_ORIGEM)
VALUES ('8', 'BULL TERRIER', 'CURTO', 'MÉDIO', 'INGLATERRA');

INSERT INTO CACHORROS (ID_RACA, NOME_RACA, TIPO_PELO, PORTE, PAIS_ORIGEM)
VALUES ('9', 'CHIHUAHUA', 'MÉDIO', 'PEQUENO', 'MÉXICO');

INSERT INTO CACHORROS (ID_RACA, NOME_RACA, TIPO_PELO, PORTE, PAIS_ORIGEM)
VALUES ('10', 'CHOW CHOW', 'MÉDIO', 'MÉDIO', 'CHINA');

INSERT INTO CACHORROS (ID_RACA, NOME_RACA, TIPO_PELO, PORTE, PAIS_ORIGEM)
VALUES ('11', 'COCKER SPANIEL', 'MÉDIO', 'MÉDIO', 'INGLATERRA');

INSERT INTO CACHORROS (ID_RACA, NOME_RACA, TIPO_PELO, PORTE, PAIS_ORIGEM)
VALUES ('12', 'DALMATA', 'CURTO', 'GRANDE', 'INGLATERRA');

INSERT INTO CACHORROS (ID_RACA, NOME_RACA, TIPO_PELO, PORTE, PAIS_ORIGEM)
VALUES ('13', 'DOBERMAN', 'CURTO', 'GRANDE', 'ALEMANHA');

INSERT INTO CACHORROS (ID_RACA, NOME_RACA, TIPO_PELO, PORTE, PAIS_ORIGEM)
VALUES ('14', 'FILA', 'CURTO', 'GRANDE', 'BRASIL');

INSERT INTO CACHORROS (ID_RACA, NOME_RACA, TIPO_PELO, PORTE, PAIS_ORIGEM)
VALUES ('15', 'FOX PAULISTINHA', 'CURTO', 'PEQUENO', 'BRASIL');

INSERT INTO CACHORROS (ID_RACA, NOME_RACA, TIPO_PELO, PORTE, PAIS_ORIGEM)
VALUES ('16', 'GOLDEN RETRIEVER', 'MÉDIO', 'GRANDE', 'ESCÓCIA');

INSERT INTO CACHORROS (ID_RACA, NOME_RACA, TIPO_PELO, PORTE, PAIS_ORIGEM)
VALUES ('17', 'HUSKY SIBERIANO', 'MÉDIO', 'GRANDE', 'RÚSSIA');

INSERT INTO CACHORROS (ID_RACA, NOME_RACA, TIPO_PELO, PORTE, PAIS_ORIGEM)
VALUES ('18', 'LABRADOR', 'CURTO', 'GRANDE', 'CANADÁ');

INSERT INTO CACHORROS (ID_RACA, NOME_RACA, TIPO_PELO, PORTE, PAIS_ORIGEM)
VALUES ('19', 'MALTÊS', 'LONGO', 'PEQUENO', 'MEDITERRÂNEO');

INSERT INTO CACHORROS (ID_RACA, NOME_RACA, TIPO_PELO, PORTE, PAIS_ORIGEM)
VALUES ('20', 'PASTOR ALEMÃO', 'CURTO', 'GRANDE', 'ALEMANHA');

--INSERIR INFORMAÇÕES NA TABELA "GATOS"
INSERT INTO GATOS (ID_RACA, NOME_RACA, TIPO_PELO, PAIS_ORIGEM)
VALUES ('1', 'PERSA', 'MÉDIO', 'IRÃ');

INSERT INTO GATOS (ID_RACA, NOME_RACA, TIPO_PELO, PAIS_ORIGEM)
VALUES ('2', 'BRITISH SHORTHAIR', 'MÉDIO', 'INGLATERRA');

INSERT INTO GATOS (ID_RACA, NOME_RACA, TIPO_PELO, PAIS_ORIGEM)
VALUES ('3', 'SPHYNX', 'MÉDIO', 'CANADÁ');

INSERT INTO GATOS (ID_RACA, NOME_RACA, TIPO_PELO, PAIS_ORIGEM)
VALUES ('4', 'SIAMÊS', 'PEQUENO', 'TAILÂNDIA');

INSERT INTO GATOS (ID_RACA, NOME_RACA, TIPO_PELO, PAIS_ORIGEM)
VALUES ('5', 'ANGORÁ', 'LONGO', 'TURQUIA');

INSERT INTO GATOS (ID_RACA, NOME_RACA, TIPO_PELO, PAIS_ORIGEM)
VALUES ('6', 'MAINE COON', 'LONGO', 'EUA');

INSERT INTO GATOS (ID_RACA, NOME_RACA, TIPO_PELO, PAIS_ORIGEM)
VALUES ('7', 'HIMALAIO', 'MÉDIO', 'INGLATERRA');

INSERT INTO GATOS (ID_RACA, NOME_RACA, TIPO_PELO, PAIS_ORIGEM)
VALUES ('8', 'BENGAL', 'CURTO', 'EUA');

INSERT INTO GATOS (ID_RACA, NOME_RACA, TIPO_PELO, PAIS_ORIGEM)
VALUES ('9', 'RAGDOLL', 'MÉDIO', 'EUA');

INSERT INTO GATOS (ID_RACA, NOME_RACA, TIPO_PELO, PAIS_ORIGEM)
VALUES ('10', 'MUNCHKIN', 'MÉDIO', 'EUA');

--SELECT CONTENDO TODAS AS INFORMAÇÕES DAS TABELAS "CACHORROS" E "GATOS"
SELECT * FROM CACHORROS;
SELECT * FROM GATOS;